### ISSUE TITLE
Deploying to Fox doesn't automatically restart the badge

### ISSUE THREAD

**Issue by MathyV** [Fri3dCamp/badge_2024_micropython#2]
You have to reset it manually after deploy

**Comment by cheops** [comment]
complicated
https://github.com/espressif/arduino-esp32/issues/6762#issuecomment-1182821492

**Comment by cheops** [comment]
micropython related: https://github.com/micropython/micropython/pull/15108

**Comment by MathyV** [comment]
It seems like there are fixes underway. This has also become less of an issue as we have switched to USB serial console: using idf.py monitor restarts the badge automatically too. The only place that it's not yet working is when launching mpremote.

Closing for now as there's not much more we can do, other than upgrading once fixes are released.
